version: '3'

services:
  nginx:
    container_name: nginx_container
    image: chaberb/nginx-ssl
    depends_on:
      - web
      - cdn
      - api
    ports:
      - "443:443"
    volumes:
      - ./nginx-uwsgi.conf:/etc/nginx/nginx.conf

  api:
    container_name: api_container
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - api/container_data/.env
      - .env/redis.env
    depends_on:
      - redis
    volumes:
      - ./api/container_data:/var/www/app

  web:
    container_name: web_container
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - web/container_data/.env
      - .env/redis.env
    depends_on:
      - redis
    volumes:
      - ./web/container_data:/var/www/app

  cdn:
    container_name: cdn_container
    build:
      context: ./cdn
      dockerfile: Dockerfile
    env_file:
      - cdn/container_data/.env
      - .env/mongo.env
      - .env/redis.env
    depends_on:
      - redis
    volumes:
      - ./cdn/container_data:/var/www/app

  redis:
    container_name: redis_container
    image: redis:latest
    volumes:
      - redis_data:/data

  mongodb:
    container_name: mongo_container
    image: mongo:latest
    env_file:
      - .env/mongo.env
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
