version: '3'

services:
  nginx:
    container_name: nginx_container
    image: chaberb/nginx-ssl
    depends_on:
      - web
      - cdn
    ports:
      - "443:443"
    volumes:
      - ./nginx-uwsgi.conf:/etc/nginx/nginx.conf

  web:
    container_name: web_container
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./web/container_data:/var/www/app

  cdn:
    container_name: cdn_container
    image: chaberb/flask-jwt
    depends_on:
      - redis
    volumes:
      - ./cdn:/var/www/app
      - ./tmp:/tmp

  redis:
    container_name: redis_container
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
