version: '3'

services:
  nginx:
    container_name: nginx_container
    image: chaberb/nginx-ssl
    depends_on:
      - client
      - server
    ports:
      - "443:443"
    volumes:
      - ./nginx-uwsgi.conf:/etc/nginx/nginx.conf

  client:
    container_name: client_container
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./client:/var/www/app

  server:
    container_name: server_container
    image: chaberb/flask-jwt
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./server:/var/www/app
      - /tmp:/tmp

  redis:
    container_name: redis_container
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:  
  redis_data:
